// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Projekt2_Aplikacja_bazodanowa_API.Migrations
{
    [DbContext(typeof(SWDatabase))]
    [Migration("20240403195750_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("StarWars.Data.Films", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("characters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("opening_crawl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("planets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("release_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("starships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("films");
                });

            modelBuilder.Entity("StarWars.Data.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("birth_year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("eye_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hair_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("homeworld")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("skin_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("starships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("people");
                });

            modelBuilder.Entity("StarWars.Data.Planets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("climate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("diameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gravity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orbital_period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("population")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("residents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rotation_period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("surface_water")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("terrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("planets");
                });

            modelBuilder.Entity("StarWars.Data.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("people")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("planets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("starships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("root");
                });

            modelBuilder.Entity("StarWars.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("average_height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("average_lifespan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("eye_colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hair_colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("homeworld")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("people")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("skin_colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("species");
                });

            modelBuilder.Entity("StarWars.Data.Starships", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MGLT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cargo_capacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cost_in_credits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("crew")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hyperdrive_rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("max_atmosphering_speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passengers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pilots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("starship_class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("starships");
                });

            modelBuilder.Entity("StarWars.Data.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cargo_capacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cost_in_credits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("crew")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("max_atmosphering_speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passengers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pilots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicle_class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
